global:
  scrape_interval: 15s        # fréquence de scrapping par défaut
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ecoblock'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
